import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { now } from "../clock.js";
import { artifactFor, projectsFor, recordRecent, saveProject, settings } from "../domain.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { locale, tr } from "../i18n.js";
registerMainMenuItem({ label: "Request revision", data: "revision:request", order: 30 });
const composer = new Composer<Ctx>();
async function tx(ctx: Ctx, key: string, english: string) { return tr(await locale(ctx), key, english); }
composer.callbackQuery("revision:request", async (ctx) => { await ctx.answerCallbackQuery(); if (!ctx.from) return; const projects = await projectsFor(String(ctx.from.id), now().getTime()); if (!projects.length) { await ctx.reply(await tx(ctx, "noProjects", "No active projects yet — create a project first, then you can request a revision."), { reply_markup: inlineKeyboard([[inlineButton(await tx(ctx, "newProject", "New project"), "project:new"), inlineButton(await tx(ctx, "mainMenu", "Main menu"), "menu:main")]]) }); return; } ctx.session.step = "revision:select"; await ctx.reply(await tx(ctx, "chooseProject", "Choose a project to revise."), { reply_markup: inlineKeyboard([...projects.slice(0, 8).map((project) => [inlineButton(project.name, `revision:select:${project.id}`)]), [inlineButton(await tx(ctx, "cancel", "Cancel"), "revision:cancel")]]) }); });
composer.callbackQuery(/^revision:select:/, async (ctx) => { await ctx.answerCallbackQuery(); if (ctx.session.step !== "revision:select") return; ctx.session.revisionProjectId = ctx.callbackQuery.data.slice(16); ctx.session.step = "revision:changes"; await ctx.reply(await tx(ctx, "changes", "Describe the changes you need. Include any framework, feature, CI, or test changes."), { reply_markup: inlineKeyboard([[inlineButton(await tx(ctx, "cancel", "Cancel"), "revision:cancel")]]) }); });
composer.callbackQuery("revision:cancel", async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.step = undefined; ctx.session.revisionProjectId = undefined; await ctx.reply(await tx(ctx, "revisionCancelled", "This revision request was cancelled.")); });
composer.callbackQuery("revision:confirm", async (ctx) => { await ctx.answerCallbackQuery(); if (!ctx.from || ctx.session.step !== "revision:confirm" || !ctx.session.revisionProjectId) return; const existing = (await projectsFor(String(ctx.from.id), now().getTime())).find((project) => project.id === ctx.session.revisionProjectId); if (!existing) { ctx.session.step = undefined; await ctx.reply("That project is no longer available. Create a new project to continue."); return; } const instant = now().getTime(); const cfg = await settings(); const id = `project-${instant}-${ctx.from.id}`; const revised = { ...existing, id, createdAt: instant, artifact: artifactFor(id, String(ctx.from.id), "project", instant, cfg.retentionDays, `${existing.name} revision`) }; await ctx.reply(await tx(ctx, "generatingRevision", "Generating your revised project now.")); await saveProject(revised); await recordRecent(id); ctx.session.step = undefined; ctx.session.revisionProjectId = undefined; const l = await locale(ctx); await ctx.reply(l === "hinglish" ? `Tumhara revised ${existing.name} scaffold ready hai. Is chat ke artifact delivery se download karo.\n\n${cfg.retentionDays} din tak available hai.` : `Your revised ${existing.name} scaffold is ready. Download it from this chat’s artifact delivery.\n\nAvailable for ${cfg.retentionDays} days.`, { reply_markup: inlineKeyboard([[inlineButton(await tx(ctx, "mainMenu", "Main menu"), "menu:main")]]) }); });
composer.on("message:text", async (ctx, next) => { if (ctx.session.step !== "revision:changes") return next(); const changes = ctx.message.text.trim(); if (changes.length < 5 || changes.length > 1000) { await ctx.reply(await tx(ctx, "invalidChanges", "Describe the changes in 5–1,000 characters.")); return; } ctx.session.step = "revision:confirm"; const l = await locale(ctx); await ctx.reply(l === "hinglish" ? `Changes review karo:\n${changes}\n\nRevision generate karein?` : `Review these changes:\n${changes}\n\nGenerate the revision?`, { reply_markup: inlineKeyboard([[inlineButton(await tx(ctx, "generateRevision", "Generate revision"), "revision:confirm"), inlineButton(await tx(ctx, "cancel", "Cancel"), "revision:cancel")]]) }); });
export default composer;
